version: '3.8'

services:
  ml-api:
    build: .
    container_name: ml-pipeline-api
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/app/dataset
      - ./model:/app/model
    restart: unless-stopped
